### PR TITLE
Update based on latest code generator.

### PR DESCRIPTION
**Pull request by jadelkhoury**

### CODE REVIEW

**Comment by jadelkhoury** [comment]
It's been more than 1 year since we updated the reference implementation.
Tested by running all 4 servers, and populating with the Client application.

**Comment by berezovskyi** [comment]
Just checked it and it looks great. Thanks Jad!

**Comment by jadelkhoury** [comment]
Thanks @berezovskyi ! 2 points worth mentioning for the future
1. I changed a model setting to **not** produce uncessary files. These were ignored anyway during runtime.
2. I changed .ignore file to not ignore *.lost files. It's important to deal with content in *.lost files to know what happened during generation.

**Comment by berezovskyi** [comment]
I use .gitignore to prevent files from being committed to git. I made a mistake once and when rolled back, I added .lost files to gitignore.

I know that use use git to see what files were changed in the folder, tracked or not. I would rather use `find . -type f -name '*.lost' -mtime -1`. But you do what's easier for you.

**Comment by berezovskyi** [comment]
@jadelkhoury what unnecessary files are you talking about?

**Comment by jadelkhoury** [comment]
> @jadelkhoury what unnecessary files are you talking about?

Under "model/src", there was a large number of source code being generator - which was not used. It's source code generated from the imported domain models. I enabled a flag in the model that tells teh generator "do not generate from imported models".
This was not visible, because it was ingored through the .ignore file :-)
https://github.com/oslc-op/refimpl/pull/153/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947L4

**Pull request merged**
