### PR TITLE
Üpdate to Lyo 6.0.0-SNAPSHOT and Java 17

### PR DESCRIPTION
**Pull request by jadelkhoury**

### CODE REVIEW

**Comment by berezovskyi** [comment]
CodeQL should also use Java 17

**Comment by berezovskyi** [comment]
See https://github.com/eclipse/lyo/commit/ec3d8fb94f698662e93b20442b1616a556c397ef

**Comment by jadelkhoury** [comment]
> See [eclipse/lyo@ec3d8fb](https://github.com/eclipse/lyo/commit/ec3d8fb94f698662e93b20442b1616a556c397ef)

Thanks @berezovskyi ! Not that I know what I am doing, but copy/paste should do it I hope :-)

**Comment by jadelkhoury** [comment]
@berezovskyi trying to fix the maven.yml file based on Lyo. But not sure what parts to copy/change. They are more significantly different.

**Comment by jadelkhoury** [comment]
@berezovskyi ! I pass all the tests, but please have a look at the changes I made to the yml-files.

**Comment by berezovskyi** [comment]
@jadelkhoury looks good to merge!

**Pull request merged**
